apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-nodeport
  namespace: mq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 32000
---

apiVersion: v1
kind: Service
metadata:
  name: clamav-nodeport
  namespace: fileman
spec:
  type: NodePort
  selector:
    app: clamav
  ports:
    - protocol: TCP
      port: 3310
      targetPort: 3310
      nodePort: 32001
---

apiVersion: v1
kind: Service
metadata:
  name: gotenberg-nodeport
  namespace: fileman
spec:
  type: NodePort
  selector:
    app: gotenberg
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32002
---

apiVersion: v1
kind: Service
metadata:
  name: azurite-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: azurite
  ports:
    - protocol: TCP
      port: 10000
      targetPort: 10000
      nodePort: 32003
---
