
# azurite [ added to default ns, due to azurite issues with DNS subdomains :'( ]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite-deploy
  namespace: default
  labels:
    app: azurite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
      - name: azurite-pod
        image: mcr.microsoft.com/azure-storage/azurite:3.31.0
        # command: ['azurite']
        # args: ['--disableProductStyleUrl']
        resources:
          limits:
            memory: 128Mi
            cpu: '2'
          requests:
            memory: 128Mi
            cpu: 40m
        env:
        # use downward api to save messing around with role permissions, etc when trying
        # to scrape and apply these simple properties later on the observability stack
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: K8S_APP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app']
        - name: K8S_POD
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
---

apiVersion: v1
kind: Service
metadata:
  name: azurite-service
spec:
  type: ClusterIP
  selector:
    app: azurite
  ports:
    - protocol: TCP
      port: 10000
---
