# portal namespace
apiVersion: v1
kind: Namespace
metadata:
  name: portal
  labels:
    name: portal
---

# development cert
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: ingress-tls-cert
  namespace: portal
data:
  tls.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNDVENDQWErZ0F3SUJBZ0lVSjdablhXRmdVRitpUUVERFQ1WGVlTzEydjFzd0NnWUlLb1pJemowRUF3SXcKTURFTE1Ba0dBMVVFQmhNQ1IwSXhDekFKQmdOVkJBb01Bbk56TVJRd0VnWURWUVFEREF0bmIyRnNaR2xuWjJWeQpjekFlRncweU5EQTRNVFF3TnpVNU16aGFGdzB6TkRBNE1UUXdOelU1TXpoYU1EUXhDekFKQmdOVkJBWVRBa2RDCk1Rc3dDUVlEVlFRS0RBSnpjekVZTUJZR0ExVUVBd3dQWjI5aGJHUnBaMmRsY25NdVpHVjJNRmt3RXdZSEtvWkkKemowQ0FRWUlLb1pJemowREFRY0RRZ0FFVzFTL3JuYVdLQ09nZjdBVUNMT1NkVnFtTVRGM2NBTDRnaWNkK1o2MApscjJlY29OQjdNTWNGZis2K1oyc2p4emhubk9RTUNJRW96RzVveEpXQlVDNjY2T0JvakNCbnpBbkJnTlZIUkVFCklEQWVnaEVxTG1kdllXeGthV2RuWlhKekxtUmxkb0lKYkc5allXeG9iM04wTUIwR0ExVWREZ1FXQkJRUHFYVDQKVTE3b21OZ3k2NzFnVHI0YTFXb1liekJWQmdOVkhTTUVUakJNb1RTa01qQXdNUXN3Q1FZRFZRUUdFd0pIUWpFTApNQWtHQTFVRUNnd0NjM014RkRBU0JnTlZCQU1NQzJkdllXeGthV2RuWlhKemdoUlFCNXlCOFlBTnF3OTJwSnFvCmdXRDJlY2Q4OHpBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlBTTN3YzJ3N1A3NzJCYU5RY0JBZFptREhhdVFaM3IKazd0YkJ1UE8vMnBlZndJaEFLMUtGRTQwL0lLZFhNUVpTZGtyOVZWbFVUQXZCQndCQ1BGZVdUa2VSeTBzCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: >-
    LS0tLS1CRUdJTiBFQyBQQVJBTUVURVJTLS0tLS0KQmdncWhrak9QUU1CQnc9PQotLS0tLUVORCBFQyBQQVJBTUVURVJTLS0tLS0KLS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUd4Mk84OGlDWXE1NVp1TXhkQXphRG1rZjlGaUY5TzdnTGk1TWxyZDdkeFdvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFVzFTL3JuYVdLQ09nZjdBVUNMT1NkVnFtTVRGM2NBTDRnaWNkK1o2MGxyMmVjb05CN01NYwpGZis2K1oyc2p4emhubk9RTUNJRW96RzVveEpXQlVDNjZ3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
---

# portal.web
apiVersion: v1
kind: ConfigMap
metadata:
  name: portalweb-config
  namespace: portal
data:
  env.js: >
    window.__env = {
      apiUrl: 'https://portalapi.goaldiggers.dev',
      b2cClientId: '3b1ad634-3c6d-4884-834f-ab8b3f5ef1ea',
      b2cSignInId: 'B2C_1_signUpOrSignIn',
      b2cTenantSubdomain: 'ne14auth',
    };
---

# portal.web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portalweb-deploy
  namespace: portal
  labels:
    app: portalweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portalweb
  template:
    metadata:
      labels:
        app: portalweb
    spec:
      containers:
      - name: portalweb-pod
        image: ne1410s/portal.web:0.0.1
        resources:
          limits:
            memory: 128Mi
            cpu: '8'
          requests:
            memory: 128Mi
            cpu: 100m
        ports:
        - containerPort: 80
        env:
        # use downward api to save messing around with role permissions, etc when trying
        # to scrape and apply these simple properties later on the observability stack
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: K8S_APP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app']
        - name: K8S_POD
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        volumeMounts:
        - name: portalweb-volume
          # this syntax is for single files only
          mountPath: /usr/share/nginx/html/env.js
          subPath: env.js
      volumes:
      - name: portalweb-volume
        configMap:
          name: portalweb-config
---
apiVersion: v1
kind: Service
metadata:
  name: portalweb-service
  namespace: portal
spec:
  type: ClusterIP
  selector:
    app: portalweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portalweb-localhost
  namespace: portal
  #annotations:
    ## Uncomment this block for 'dynamic' tls (must be hosted cluster)
    #cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - portal.goaldiggers.dev
    secretName: ingress-tls-cert
  rules:
  - host: portal.goaldiggers.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portalweb-service
            port:
              number: 80
status:
  loadBalancer:
    ingress:
    - hostname: localhost
---

# portal.api
apiVersion: v1
kind: ConfigMap
metadata:
  name: portalapi-config
  namespace: portal
data:
  HostedBaseUrl: "http://localhost:8080"
  AzureClients__Ephemeral: "UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://azurite;"
  AzureClients__Permanent: "UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://azurite;"
  OpenTel__Grpc: "http://otel-collector.monitoring:4317"
  RabbitMq__Hostname: "rabbitmq.mq"
  RabbitMq__Port: "5672"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: portalapi-deploy
  namespace: portal
  labels:
    app: portalapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portalapi
  template:
    metadata:
      labels:
        app: portalapi
    spec:
      containers:
      - name: portalapi-pod
        image: ne1410s/portal.api:0.0.1
        resources:
          limits:
            memory: 256Mi
            cpu: '8'
          requests:
            memory: 256Mi
            cpu: 40m
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: portalapi-config
        env:
        # use downward api to save messing around with role permissions, etc when trying
        # to scrape and apply these simple properties later on the observability stack
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: K8S_APP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app']
        - name: K8S_POD
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          failureThreshold: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 8080
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 8080
          failureThreshold: 1
          periodSeconds: 45
---
apiVersion: v1
kind: Service
metadata:
  name: portalapi-service
  namespace: portal
spec:
  type: ClusterIP
  selector:
    app: portalapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portalapi-localhost
  namespace: portal
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    # Uncomment below for 'dynamic' tls (must be hosted cluster)
    #cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - portalapi.goaldiggers.dev
    secretName: ingress-tls-cert
  rules:
  - host: portalapi.goaldiggers.dev
    http:
      paths:
      - backend:
          service:
            name: portalapi-service
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: localhost
---
# allows us to hit up "azurite" (single hostname in default ns) from anywhere in this ns - just to make azurite work!
apiVersion: v1
kind: Service
metadata:
  name: azurite
  namespace: portal
spec:
  type: ExternalName
  externalName: azurite-service.default.svc.cluster.local
---