adminUser: admin
adminPassword: admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Tempo
      type: tempo
      editable: false
      url: http://tempo:3100
    - name: Prometheus
      type: prometheus
      editable: false
      url: http://prometheus-server:80
    - name: Loki
      type: loki
      editable: false
      url: http://loki-gateway
      jsonData:
        httpHeaderName1: X-Scope-OrgID
      secureJsonData:
        httpHeaderValue1: 1

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: default
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    loki:
      json: |
        {
          "annotations": {
            "list": [
              {
                "$$hashKey": "object:75",
                "builtIn": 1,
                "datasource": {
                  "type": "datasource",
                  "uid": "grafana"
                },
                "enable": true,
                "hide": true,
                "iconColor": "rgba(0, 211, 255, 1)",
                "name": "Annotations & Alerts",
                "type": "dashboard"
              }
            ]
          },
          "description": "Loki logs panel with prometheus variables ",
          "editable": true,
          "fiscalYearStartMonth": 0,
          "gnetId": 12019,
          "graphTooltip": 0,
          "id": 3,
          "links": [],
          "panels": [
            {
              "datasource": {
                "type": "loki",
                "uid": "P8E80F9AEF21F6940"
              },
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisBorderShow": false,
                    "axisCenteredZero": false,
                    "axisColorMode": "text",
                    "axisLabel": "",
                    "axisPlacement": "hidden",
                    "barAlignment": 0,
                    "drawStyle": "bars",
                    "fillOpacity": 100,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "insertNulls": false,
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "never",
                    "spanNulls": false,
                    "stacking": {
                      "group": "A",
                      "mode": "none"
                    },
                    "thresholdsStyle": {
                      "mode": "off"
                    }
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green"
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  },
                  "unit": "short"
                },
                "overrides": []
              },
              "gridPos": {
                "h": 3,
                "w": 24,
                "x": 0,
                "y": 0
              },
              "id": 6,
              "options": {
                "legend": {
                  "calcs": [],
                  "displayMode": "list",
                  "placement": "bottom",
                  "showLegend": false
                },
                "tooltip": {
                  "mode": "multi",
                  "sort": "none"
                }
              },
              "targets": [
                {
                  "datasource": {
                    "type": "loki",
                    "uid": "P8E80F9AEF21F6940"
                  },
                  "expr": "sum(count_over_time({namespace=\"$namespace\", instance=~\"$pod\"} |~ \"$search\"[$__interval]))",
                  "refId": "A"
                }
              ],
              "type": "timeseries"
            },
            {
              "datasource": {
                "type": "loki",
                "uid": "P8E80F9AEF21F6940"
              },
              "gridPos": {
                "h": 25,
                "w": 24,
                "x": 0,
                "y": 3
              },
              "id": 2,
              "maxDataPoints": "",
              "options": {
                "dedupStrategy": "none",
                "enableLogDetails": true,
                "prettifyLogMessage": false,
                "showCommonLabels": false,
                "showLabels": false,
                "showTime": true,
                "sortOrder": "Descending",
                "wrapLogMessage": true
              },
              "targets": [
                {
                  "datasource": {
                    "type": "loki",
                    "uid": "P8E80F9AEF21F6940"
                  },
                  "expr": "{namespace=\"$namespace\", instance=~\"$pod\"} |~ \"$search\"",
                  "refId": "A"
                }
              ],
              "title": "Logs Panel",
              "type": "logs"
            },
            {
              "content": "<div style=\"text-align:center\"> For Grafana Loki blog example </div>\n\n\n",
              "datasource": {
                "type": "datasource",
                "uid": "grafana"
              },
              "gridPos": {
                "h": 3,
                "w": 24,
                "x": 0,
                "y": 28
              },
              "id": 4,
              "mode": "html",
              "targets": [
                {
                  "datasource": {
                    "type": "datasource",
                    "uid": "grafana"
                  },
                  "refId": "A"
                }
              ],
              "transparent": true,
              "type": "text"
            }
          ],
          "schemaVersion": 39,
          "tags": [],
          "templating": {
            "list": [
              {
                "current": {
                  "selected": false,
                  "text": "cert-manager",
                  "value": "cert-manager"
                },
                "datasource": {
                  "type": "prometheus",
                  "uid": "PBFA97CFB590B2093"
                },
                "definition": "label_values(kube_pod_info, namespace)",
                "hide": 0,
                "includeAll": false,
                "multi": false,
                "name": "namespace",
                "options": [],
                "query": "label_values(kube_pod_info, namespace)",
                "refresh": 1,
                "regex": "",
                "skipUrlSync": false,
                "sort": 0,
                "tagValuesQuery": "",
                "tagsQuery": "",
                "type": "query",
                "useTags": false
              },
              {
                "allValue": ".*",
                "current": {
                  "selected": false,
                  "text": "All",
                  "value": "$__all"
                },
                "datasource": {
                  "type": "prometheus",
                  "uid": "PBFA97CFB590B2093"
                },
                "definition": "label_values(container_network_receive_bytes_total{namespace=~\"$namespace\"},pod)",
                "hide": 0,
                "includeAll": true,
                "multi": true,
                "name": "pod",
                "options": [],
                "query": "label_values(container_network_receive_bytes_total{namespace=~\"$namespace\"},pod)",
                "refresh": 1,
                "regex": "",
                "skipUrlSync": false,
                "sort": 0,
                "tagValuesQuery": "",
                "tagsQuery": "",
                "type": "query",
                "useTags": false
              },
              {
                "current": {
                  "selected": false,
                  "text": "level=warn",
                  "value": "level=warn"
                },
                "hide": 0,
                "name": "search",
                "options": [
                  {
                    "selected": true,
                    "text": "level=warn",
                    "value": "level=warn"
                  }
                ],
                "query": "level=warn",
                "skipUrlSync": false,
                "type": "textbox"
              }
            ]
          },
          "time": {
            "from": "now-30m",
            "to": "now"
          },
          "timepicker": {
            "refresh_intervals": [
              "5s",
              "10s",
              "30s",
              "1m",
              "5m",
              "15m",
              "30m",
              "1h",
              "2h",
              "1d"
            ]
          },
          "timezone": "",
          "title": "Loki Dashboard quick search",
          "uid": "lizz0RiZz",
          "version": 2,
          "weekStart": ""
        }

