adminUser: admin
adminPassword: admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Tempo
      type: tempo
      uid: tempo_src_001
      editable: false
      url: http://tempo:3100
    - name: Prometheus
      type: prometheus
      uid: prom_src_001
      editable: false
      url: http://prometheus-server
    - name: Loki
      type: loki
      uid: loki_src_001
      editable: false
      url: http://loki-gateway
      jsonData:
        httpHeaderName1: X-Scope-OrgID
      secureJsonData:
        httpHeaderValue1: 1

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: default
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    loki:
      json: |
        {
          "__elements": {},
          "__requires": [
            {
              "type": "grafana",
              "id": "grafana",
              "name": "Grafana",
              "version": "11.1.0"
            },
            {
              "type": "panel",
              "id": "logs",
              "name": "Logs",
              "version": ""
            },
            {
              "type": "datasource",
              "id": "loki",
              "name": "Loki",
              "version": "1.0.0"
            },
            {
              "type": "panel",
              "id": "timeseries",
              "name": "Time series",
              "version": ""
            }
          ],
          "annotations": {
            "list": [
              {
                "$$hashKey": "object:75",
                "builtIn": 1,
                "datasource": {
                  "type": "datasource",
                  "uid": "grafana"
                },
                "enable": true,
                "hide": true,
                "iconColor": "rgba(0, 211, 255, 1)",
                "name": "Annotations & Alerts",
                "target": {
                  "limit": 100,
                  "matchAny": false,
                  "tags": [],
                  "type": "dashboard"
                },
                "type": "dashboard"
              }
            ]
          },
          "description": "Loki Logs",
          "editable": true,
          "fiscalYearStartMonth": 3,
          "gnetId": 12019,
          "graphTooltip": 0,
          "id": null,
          "links": [],
          "liveNow": false,
          "panels": [
            {
              "datasource": {
                "type": "loki",
                "uid": "loki_src_001"
              },
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisBorderShow": false,
                    "axisCenteredZero": false,
                    "axisColorMode": "text",
                    "axisLabel": "",
                    "axisPlacement": "hidden",
                    "barAlignment": 0,
                    "drawStyle": "bars",
                    "fillOpacity": 100,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "insertNulls": false,
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "never",
                    "spanNulls": false,
                    "stacking": {
                      "group": "A",
                      "mode": "none"
                    },
                    "thresholdsStyle": {
                      "mode": "off"
                    }
                  },
                  "links": [],
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": null
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  },
                  "unit": "short"
                },
                "overrides": []
              },
              "gridPos": {
                "h": 3,
                "w": 24,
                "x": 0,
                "y": 0
              },
              "id": 6,
              "options": {
                "legend": {
                  "calcs": [],
                  "displayMode": "list",
                  "placement": "bottom",
                  "showLegend": false
                },
                "tooltip": {
                  "mode": "multi",
                  "sort": "none"
                }
              },
              "pluginVersion": "10.2.2",
              "targets": [
                {
                  "datasource": {
                    "type": "loki",
                    "uid": "loki_src_001"
                  },
                  "expr": "sum(count_over_time({namespace=\"$var_namespace\", app=~\"$var_app\", pod=~\"$var_instance\"} |~ \"$var_search\"[$__interval]))",
                  "refId": "A"
                }
              ],
              "type": "timeseries"
            },
            {
              "datasource": {
                "type": "loki",
                "uid": "loki_src_001"
              },
              "gridPos": {
                "h": 25,
                "w": 24,
                "x": 0,
                "y": 3
              },
              "id": 2,
              "maxDataPoints": "",
              "options": {
                "dedupStrategy": "none",
                "enableLogDetails": true,
                "prettifyLogMessage": false,
                "showCommonLabels": false,
                "showLabels": false,
                "showTime": true,
                "sortOrder": "Descending",
                "wrapLogMessage": true
              },
              "targets": [
                {
                  "datasource": {
                    "type": "loki",
                    "uid": "loki_src_001"
                  },
                  "expr": "{namespace=\"$var_namespace\", app=~\"$var_app\", pod=~\"$var_instance\"} |~ \"$var_search\"",
                  "refId": "A"
                }
              ],
              "title": "Logs Panel",
              "type": "logs"
            }
          ],
          "refresh": "",
          "schemaVersion": 39,
          "tags": [],
          "templating": {
            "list": [
              {
                "current": {},
                "datasource": {
                  "type": "loki",
                  "uid": "loki_src_001"
                },
                "definition": "",
                "hide": 0,
                "includeAll": false,
                "label": "Namespace",
                "multi": false,
                "name": "var_namespace",
                "options": [],
                "query": {
                  "label": "namespace",
                  "refId": "LokiVariableQueryEditor-VariableQuery",
                  "stream": "",
                  "type": 1
                },
                "refresh": 1,
                "regex": "",
                "skipUrlSync": false,
                "sort": 0,
                "tagValuesQuery": "",
                "tagsQuery": "",
                "type": "query",
                "useTags": false
              },
              {
                "allValue": ".*",
                "current": {},
                "datasource": {
                  "type": "loki",
                  "uid": "loki_src_001"
                },
                "definition": "",
                "hide": 0,
                "includeAll": true,
                "label": "App",
                "multi": false,
                "name": "var_app",
                "options": [],
                "query": {
                  "label": "app",
                  "refId": "LokiVariableQueryEditor-VariableQuery",
                  "stream": "{namespace=\"$var_namespace\"}",
                  "type": 1
                },
                "refresh": 1,
                "regex": "",
                "skipUrlSync": false,
                "sort": 0,
                "tagValuesQuery": "",
                "tagsQuery": "",
                "type": "query",
                "useTags": false
              },
              {
                "allValue": ".*",
                "current": {},
                "datasource": {
                  "type": "loki",
                  "uid": "loki_src_001"
                },
                "definition": "",
                "hide": 0,
                "includeAll": true,
                "label": "Pod",
                "multi": false,
                "name": "var_instance",
                "options": [],
                "query": {
                  "label": "pod",
                  "refId": "LokiVariableQueryEditor-VariableQuery",
                  "stream": "{namespace=\"$var_namespace\", app=~\"$var_app\"}",
                  "type": 1
                },
                "refresh": 1,
                "regex": "",
                "skipUrlSync": false,
                "sort": 0,
                "tagValuesQuery": "",
                "tagsQuery": "",
                "type": "query",
                "useTags": false
              },
              {
                "current": {
                  "selected": false,
                  "text": "",
                  "value": ""
                },
                "hide": 0,
                "label": "Text Search",
                "name": "var_search",
                "options": [
                  {
                    "selected": true,
                    "text": "",
                    "value": ""
                  }
                ],
                "query": "",
                "skipUrlSync": false,
                "type": "textbox"
              }
            ]
          },
          "time": {
            "from": "now-30m",
            "to": "now"
          },
          "timepicker": {
            "refresh_intervals": [
              "5s",
              "10s",
              "30s",
              "1m"
            ]
          },
          "timezone": "",
          "title": "Loki Logs",
          "uid": "lizz0RaZZ",
          "version": 1,
          "weekStart": "monday"
        }
