command:
  name: otelcol-contrib
mode: deployment # <daemonset|deployment|statefulset>
image:
  repository: otel/opentelemetry-collector-contrib
config:
  receivers:
    loki:
      use_incoming_timestamp: true
      protocols:
        http:
          endpoint: localhost:3500
        #grpc:
        #  endpoint: localhost:3600
    otlp:
      protocols:
        grpc:
          endpoint: localhost:4317
        http:
          endpoint: localhost:4318

  processors:
    attributes/logs:
      actions:
      - action: insert
        key: loki.attribute.labels
        value: namespace, app, pod, job
      - action: insert
        key: loki.format
        value: raw
    # attributes/metrics:
    #   actions:
    #   - action: delete
    #     key: instance

  exporters:
    loki:
      endpoint: http://loki-gateway/loki/api/v1/push
      tls:
        insecure: true
    # prometheus:
    #   endpoint: localhost:59090
    otlphttp:
      endpoint: http://tempo:4318
      tls:
        insecure: true

  extensions:
    zpages: {}
    health_check: {}

  service:
    extensions: [zpages, health_check]
    pipelines:
      logs:
        receivers: [loki]
        processors: [attributes/logs]
        exporters: [loki]
      # metrics:
      #   receivers: [otlp]
      #   # processors: [attributes/metrics]
      #   exporters: [prometheus]
      traces:
        receivers: [otlp]
        exporters: [otlphttp]
ports:
  otel-zpages:
    enabled: true
    containerPort: 55679
    servicePort: 55679
    hostPort: 55679
  otel-loki:
    enabled: true
    protocol: TCP
    containerPort: 3500
    servicePort: 3500
    hostPort: 3500
  # prevent unneeded ports from being opened
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
resources:
  limits:
    cpu: 250m
    memory: 512Mi
