prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
server:
  global:
    scrape_interval: 30s
    scrape_timeout: 10s
    evaluation_interval: 1m
  extraArgs:
    web.enable-remote-write-receiver: null

# adds additional scrape configs to prometheus.yml
# must be a string so you have to add a | after extraScrapeConfigs:
extraScrapeConfigs: |
  - job_name: otel-metrics
    scrape_interval: 10s
    static_configs:
    - targets:
      - otel-collector.monitoring:59090
  - job_name: rabbitmq
    scrape_interval: 10s
    static_configs:
    - targets:
      - rabbitmq.mq:9419