deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  limits_config:
    ingestion_rate_mb: 6
    ingestion_burst_size_mb: 8
  storage:
    type: 'filesystem'
  schemaConfig:
    configs:
      - object_store: filesystem
        store: tsdb
singleBinary:
  replicas: 1
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
