datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Tempo
      type: tempo
      editable: false
      url: http://tempo:3100
    - name: Prometheus
      type: prometheus
      editable: false
      url: http://prometheus-server:80
    - name: Loki
      type: loki
      editable: false
      url: http://loki-gateway
      jsonData:
        httpHeaderName1: X-Scope-OrgID
      secureJsonData:
        httpHeaderValue1: 1