command:
  name: otelcol-contrib
mode: deployment # <daemonset|deployment|statefulset>
image:
  repository: otel/opentelemetry-collector-contrib
config:
  receivers:
    loki/promtail:
      protocols:
        http:
      use_incoming_timestamp: true
    otlp:
      protocols:
        grpc: {}
        http: {}
  
  processors:
    attributes/logs:
      actions:
      - action: insert
        key: loki.attribute.labels
        value: namespace, app, pod, job
      - action: insert
        key: loki.format
        value: raw
    # attributes/metrics:
    #   actions:
    #   - action: delete
    #     key: instance

  exporters:
    loki:
      endpoint: http://loki-gateway/loki/api/v1/push
      tls:
        insecure: true
    prometheus:
      endpoint: ':59090'
    otlp/tempo:
      endpoint: tempo:4317
      tls:
        insecure: true
    otlp/jaeger:
      endpoint: jaeger-collector:4317
      tls:
        insecure: true
  
  extensions:
    zpages: {}
    health_check: {}
  
  service:
    extensions: [zpages, health_check]
    pipelines:
      logs:
        receivers: [loki/promtail]
        processors: [attributes/logs]
        exporters: [loki]
      metrics:
        receivers: [otlp]
        # processors: [attributes/metrics]
        exporters: [prometheus]
      traces:
        receivers: [otlp]
        exporters: [otlp/tempo, otlp/jaeger]
ports:
  otel-zpages:
    enabled: true
    containerPort: 55679
    servicePort: 55679
    hostPort: 55679
  otel-loki:
    enabled: true
    containerPort: 3500
    servicePort: 3500
    hostPort: 3500
resources:
  limits:
    cpu: 250m
    memory: 512Mi