# development cert
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: ingress-tls-cert
  namespace: mq
data:
  tls.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNDVENDQWErZ0F3SUJBZ0lVSjdablhXRmdVRitpUUVERFQ1WGVlTzEydjFzd0NnWUlLb1pJemowRUF3SXcKTURFTE1Ba0dBMVVFQmhNQ1IwSXhDekFKQmdOVkJBb01Bbk56TVJRd0VnWURWUVFEREF0bmIyRnNaR2xuWjJWeQpjekFlRncweU5EQTRNVFF3TnpVNU16aGFGdzB6TkRBNE1UUXdOelU1TXpoYU1EUXhDekFKQmdOVkJBWVRBa2RDCk1Rc3dDUVlEVlFRS0RBSnpjekVZTUJZR0ExVUVBd3dQWjI5aGJHUnBaMmRsY25NdVpHVjJNRmt3RXdZSEtvWkkKemowQ0FRWUlLb1pJemowREFRY0RRZ0FFVzFTL3JuYVdLQ09nZjdBVUNMT1NkVnFtTVRGM2NBTDRnaWNkK1o2MApscjJlY29OQjdNTWNGZis2K1oyc2p4emhubk9RTUNJRW96RzVveEpXQlVDNjY2T0JvakNCbnpBbkJnTlZIUkVFCklEQWVnaEVxTG1kdllXeGthV2RuWlhKekxtUmxkb0lKYkc5allXeG9iM04wTUIwR0ExVWREZ1FXQkJRUHFYVDQKVTE3b21OZ3k2NzFnVHI0YTFXb1liekJWQmdOVkhTTUVUakJNb1RTa01qQXdNUXN3Q1FZRFZRUUdFd0pIUWpFTApNQWtHQTFVRUNnd0NjM014RkRBU0JnTlZCQU1NQzJkdllXeGthV2RuWlhKemdoUlFCNXlCOFlBTnF3OTJwSnFvCmdXRDJlY2Q4OHpBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlBTTN3YzJ3N1A3NzJCYU5RY0JBZFptREhhdVFaM3IKazd0YkJ1UE8vMnBlZndJaEFLMUtGRTQwL0lLZFhNUVpTZGtyOVZWbFVUQXZCQndCQ1BGZVdUa2VSeTBzCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: >-
    LS0tLS1CRUdJTiBFQyBQQVJBTUVURVJTLS0tLS0KQmdncWhrak9QUU1CQnc9PQotLS0tLUVORCBFQyBQQVJBTUVURVJTLS0tLS0KLS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUd4Mk84OGlDWXE1NVp1TXhkQXphRG1rZjlGaUY5TzdnTGk1TWxyZDdkeFdvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFVzFTL3JuYVdLQ09nZjdBVUNMT1NkVnFtTVRGM2NBTDRnaWNkK1o2MGxyMmVjb05CN01NYwpGZis2K1oyc2p4emhubk9RTUNJRW96RzVveEpXQlVDNjZ3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitui-localhost
  namespace: mq
  #annotations:
    ## Uncomment this block for 'dynamic' tls (must be hosted cluster)
    #cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - rabbit.goaldiggers.dev
    secretName: ingress-tls-cert
  rules:
  - host: rabbit.goaldiggers.dev
    http:
      paths:
      - backend:
          service:
            name: rabbitmq
            port:
              number: 15672
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: localhost
---
