repositories:

- name: jetstack
  url: https://charts.jetstack.io

- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx


releases:

- name: cert-manager
  chart: jetstack/cert-manager
  version: v1.15.2
  namespace: cert-manager
  set:
  - name: crds.enabled
    value: true

- name: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: 4.11.1
  namespace: ingress-nginx

