repositories:

- name: jetstack
  url: https://charts.jetstack.io

- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

- name: grafana
  url: https://grafana.github.io/helm-charts


releases:

- name: cert-manager
  chart: jetstack/cert-manager
  version: v1.15.2
  namespace: cert-manager
  set:
  - name: crds.enabled
    value: true

- name: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: 4.11.1
  namespace: ingress-nginx

- name: prometheus
  chart: prometheus-community/prometheus
  version: 25.25.0
  namespace: monitoring
  set:
  - name: prometheus-node-exporter.hostRootFsMount.enabled
    value: false

- name: grafana
  chart: grafana/grafana
  version: 8.4.0
  namespace: monitoring
  values:
  - ../values/grafana-values.yaml

- name: monitoring-ingresses
  chart: ../manifests/monitoring-ingresses
  namespace: monitoring

- name: promtail
  chart: ../manifests/promtail
  namespace: monitoring

- name: loki
  chart: grafana/loki
  version: 6.7.3
  namespace: monitoring
  values:
  - ../values/loki-values.yaml

- name: tempo
  chart: grafana/tempo
  version: 1.10.1
  namespace: monitoring

- name: my-apps
  chart: ../manifests/my-apps
