repositories:

- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

- name: grafana
  url: https://grafana.github.io/helm-charts

- name: bitnami
  url: https://charts.bitnami.com/bitnami


releases:

- name: prometheus
  chart: prometheus-community/prometheus
  version: 25.25.0
  namespace: monitoring
  values: [../values/prometheus-values.yaml]

- name: grafana
  chart: grafana/grafana
  version: 8.4.0
  namespace: monitoring
  values: [../values/grafana-values.yaml]

- name: tempo
  chart: grafana/tempo
  version: 1.10.1
  namespace: monitoring
  values: [../values/tempo-values.yaml]

- name: promtail
  chart: ../manifests/promtail
  namespace: monitoring
  needs: [monitoring/prometheus]

- name: loki
  chart: grafana/loki
  version: 6.7.3
  namespace: monitoring
  needs: [monitoring/prometheus]
  values: [../values/loki-values.yaml]

- name: rabbitmq
  chart: bitnami/rabbitmq
  version: 14.6.6
  namespace: mq
  needs: [monitoring/prometheus]
  values: [../values/rabbitmq-values.yaml]

- name: my-apps
  chart: ../manifests/my-apps
  needs: [mq/rabbitmq]