repositories:

- name: otel
  url: https://open-telemetry.github.io/opentelemetry-helm-charts


releases:

- name: opentelemetry-operator
  chart: otel/opentelemetry-operator
  version: 0.66.0
  namespace: monitoring
  set:
  - name: manager.collectorImage.repository
    value: otel/opentelemetry-collector-contrib
  - name: admissionWebhooks.certManager.enabled
    value: true

- name: opentelemetry-collector
  chart: otel/opentelemetry-collector
  version: 0.101.2
  namespace: monitoring
  values:
  - ../values/otel-collector-values.yaml

