repositories:

- name: otel
  url: https://open-telemetry.github.io/opentelemetry-helm-charts


releases:

- name: opentelemetry-collector
  chart: otel/opentelemetry-collector
  version: 0.101.2
  namespace: monitoring
  values:
  - ../values/otel-collector-values.yaml
